#!/usr/bin/env python3
"""Tool package with a safe dispatch facade and compatibility re-exports.

``dispatch_registered_tool`` is the application-facing execution boundary.
The raw provider/process names are retained for existing integrations and are
enumerated in ``DEPRECATED_TOOL_EXPORTS`` for machine-readable migration.
"""

from types import MappingProxyType

from core.credentials import register_credential
from core.tools.base import (
    C_BLUE,
    C_CYAN,
    C_GREEN,
    C_GREY,
    C_MAGENTA,
    C_RED,
    C_RESET,
    C_YELLOW,
    ToolResult,
    _fmt_elapsed,
    get_tool_config,
    is_tool_available,
    run_tool,
)
from core.tools.exploit_tools import (
    _is_internal_ip,
    _merge_wordlists,
    get_all_known_creds_for_target,
    get_best_creds_for_target,
    get_known_creds,
    run_bruteforce,
    run_jmx2rce_cleanup,
    run_jmx2rce_rce,
    run_jmx2rce_read,
    run_jmx2rce_scan,
    run_web_login_bruteforce,
)
from core.tools.post_tools import (
    _run_crack_hashes,
    _run_killchain_interactive,
    _run_killchain_stage,
    _run_shodan_host,
    _run_shodan_interactive,
    _run_shodan_range,
    _run_shodan_vulns,
    _run_ssh_session_interactive,
    _run_waf_detect,
    run_default_recon,
)
from core.tools.public import dispatch_registered_tool
from core.tools.quarantined import QUARANTINED_CAPABILITY_NAMES
from core.tools.recon_tools import (
    run_curl_headers,
    run_dig,
    run_dirb,
    run_enum4linux,
    run_ffuf,
    run_ftp_anonymous_check,
    run_gobuster,
    run_nikto,
    run_nmap,
    run_rustscan,
    run_scrapling_crawl,
    run_scrapling_fetch,
    run_smbclient,
    run_smtp_probe,
    run_sqlmap,
    run_ssh_user_enum,
    run_sslscan,
    run_whatweb,
    run_whois,
    run_wpscan,
)
from core.tools.registry import get_all_names as _get_all_tool_names
from core.tools.runner import (
    TOOLS_MENU,
    format_recon_for_llm,
    interactive_tool_run,
    run_arbitrary_cmd,
    run_managed_shell,
    run_python_repl,
    run_single_tool,
    run_tool_by_command,
)

# Immutable process-start snapshot used by runtime-contract checks. Dynamic
# plugin/test registrations remain available through the live registry without
# changing what this release advertises as its built-in tool set.
BUILTIN_TOOL_NAMES = tuple(_get_all_tool_names())

# Compatibility metadata is deliberately explicit.  It prevents documentation
# and integration checks from treating a raw provider or process helper as the
# preferred public execution boundary while preserving every historical import.
LOW_LEVEL_EXECUTION_EXPORTS = (
    "TOOLS_MENU",
    "interactive_tool_run",
    "run_arbitrary_cmd",
    "run_managed_shell",
    "run_python_repl",
    "run_single_tool",
    "run_tool",
    "run_tool_by_command",
)
DIRECT_PROVIDER_EXPORTS = (
    "_run_crack_hashes",
    "_run_killchain_interactive",
    "_run_killchain_stage",
    "_run_shodan_host",
    "_run_shodan_interactive",
    "_run_shodan_range",
    "_run_shodan_vulns",
    "_run_ssh_session_interactive",
    "_run_waf_detect",
    "run_bruteforce",
    "run_curl_headers",
    "run_default_recon",
    "run_dig",
    "run_dirb",
    "run_enum4linux",
    "run_ffuf",
    "run_ftp_anonymous_check",
    "run_gobuster",
    "run_jmx2rce_cleanup",
    "run_jmx2rce_rce",
    "run_jmx2rce_read",
    "run_jmx2rce_scan",
    "run_nikto",
    "run_nmap",
    "run_rustscan",
    "run_scrapling_crawl",
    "run_scrapling_fetch",
    "run_smbclient",
    "run_smtp_probe",
    "run_sqlmap",
    "run_ssh_user_enum",
    "run_sslscan",
    "run_web_login_bruteforce",
    "run_whatweb",
    "run_whois",
    "run_wpscan",
)
DEPRECATED_TOOL_EXPORTS = MappingProxyType(
    dict.fromkeys(
        (*LOW_LEVEL_EXECUTION_EXPORTS, *DIRECT_PROVIDER_EXPORTS),
        "Use core.tools.dispatch_registered_tool with an ExecutionContext",
    ),
)

__all__ = [
    "BUILTIN_TOOL_NAMES",
    "C_BLUE",
    "C_CYAN",
    "C_GREEN",
    "C_GREY",
    "C_MAGENTA",
    "C_RED",
    "C_RESET",
    "C_YELLOW",
    "DEPRECATED_TOOL_EXPORTS",
    "DIRECT_PROVIDER_EXPORTS",
    "LOW_LEVEL_EXECUTION_EXPORTS",
    "QUARANTINED_CAPABILITY_NAMES",
    "TOOLS_MENU",
    "ToolResult",
    "_fmt_elapsed",
    "_is_internal_ip",
    "_merge_wordlists",
    "_run_crack_hashes",
    "_run_killchain_interactive",
    "_run_killchain_stage",
    "_run_shodan_host",
    "_run_shodan_interactive",
    "_run_shodan_range",
    "_run_shodan_vulns",
    "_run_ssh_session_interactive",
    "_run_waf_detect",
    "dispatch_registered_tool",
    "format_recon_for_llm",
    "get_all_known_creds_for_target",
    "get_best_creds_for_target",
    "get_known_creds",
    "get_tool_config",
    "interactive_tool_run",
    "is_tool_available",
    "register_credential",
    "run_arbitrary_cmd",
    "run_bruteforce",
    "run_curl_headers",
    "run_default_recon",
    "run_dig",
    "run_dirb",
    "run_enum4linux",
    "run_ffuf",
    "run_ftp_anonymous_check",
    "run_gobuster",
    "run_jmx2rce_cleanup",
    "run_jmx2rce_rce",
    "run_jmx2rce_read",
    "run_jmx2rce_scan",
    "run_managed_shell",
    "run_nikto",
    "run_nmap",
    "run_python_repl",
    "run_rustscan",
    "run_scrapling_crawl",
    "run_scrapling_fetch",
    "run_single_tool",
    "run_smbclient",
    "run_smtp_probe",
    "run_sqlmap",
    "run_ssh_user_enum",
    "run_sslscan",
    "run_tool",
    "run_tool_by_command",
    "run_web_login_bruteforce",
    "run_whatweb",
    "run_whois",
    "run_wpscan",
]
